export const LOAD_ARTISTS_SUCCESS = "LOAD_ARTISTS_SUCCESS";
export const LOAD_ALBUMS_SUCCESS = "LOAD_ALBUMS_SUCCESS";
export const SEARCH_ARTIST_SUCCESS = "SEARCH_ARTIST_SUCCESS";
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";
export const FILTER_ARTISTS = "FILTER_ARTISTS";
